// This file was generated by executing this statement: wav2c wavFiles/p1FrozenN.wav
extern uint16_t p1Frozen_wav[];
#define P1FROZENN_WAV_SAMPLE_RATE 480000
#define P1FROZENN_WAV_BITS_PER_SAMPLE 16
#define P1FROZENN_WAV_NUMBER_OF_SAMPLES 105230
