// This file was generated by executing this statement: wav2c p1Unfrozen.wav
extern uint16_t p1Unfrozen_wav[];
#define P1UNFROZEN_WAV_SAMPLE_RATE 480000
#define P1UNFROZEN_WAV_BITS_PER_SAMPLE 16
#define P1UNFROZEN_WAV_NUMBER_OF_SAMPLES 109889
