// This file was generated by executing this statement: wav2c p2Frozen.wav
extern uint16_t p2Frozen_wav[];
#define P2FROZEN_WAV_SAMPLE_RATE 480000
#define P2FROZEN_WAV_BITS_PER_SAMPLE 16
#define P2FROZEN_WAV_NUMBER_OF_SAMPLES 97742
