// This file was generated by executing this statement: wav2c p3Frozen.wav
extern uint16_t p3Frozen_wav[];
#define P3FROZEN_WAV_SAMPLE_RATE 480000
#define P3FROZEN_WAV_BITS_PER_SAMPLE 16
#define P3FROZEN_WAV_NUMBER_OF_SAMPLES 69806
