// This file was generated by executing this statement: wav2c p4Frozen.wav
extern uint16_t p4Frozen_wav[];
#define P4FROZEN_WAV_SAMPLE_RATE 480000
#define P4FROZEN_WAV_BITS_PER_SAMPLE 16
#define P4FROZEN_WAV_NUMBER_OF_SAMPLES 62176
