// This file was generated by executing this statement: wav2c p4Unfrozen.wav
extern uint16_t p4Unfrozen_wav[];
#define P4UNFROZEN_WAV_SAMPLE_RATE 480000
#define P4UNFROZEN_WAV_BITS_PER_SAMPLE 16
#define P4UNFROZEN_WAV_NUMBER_OF_SAMPLES 73971
